# NumPy

**Creator : Gian Antariksa**

Source  : 

Jose Portilla [Python for Data Science and Machinee Learning Bootcamp](https://www.udemy.com/python-for-data-science-and-machine-learning-bootcamp/)

NumPy adalah Library untuk Linear Algebra (Aljabar Linear) dalam Python, alasannya mengapa sangat penting dalam Data Science adalah hampir semua libraries dalam PyData Ecosystem bergantung terhadap NumPy.

Kita akan mempelajari Dasar Dasar dari NumPy, jadi dimulai dengan menginstallnya!

## Instruksi Instalasi

**Sangat dianjurkan dalam menginstalasi Python menggunakan Anaconda. Jika sudah memiliki Anaconda, install NumPy dengan membuka Anaconda Prompt dengan mengetik**
    
    conda install numpy
    
**Jika belum memiliki Anaconda dan tidak bisa menginstall bisa mengacu pada**

[Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

## Menggunakan NumPy

Dalam menggunakan NumPy kamu dapat melakukan import sebagai library :

In [3]:
import numpy as np

NumPy memiliki berbagai macam fungsi dan kemampuan. Dalam hal ini kita tidak dapat mempelajari semuanya, tetapi kita akan mendalami beberapa materi penting dari NumPy:

-Vectors, Arrays, Matrices, dan Number Generation

## Numpy Arrays
NumPy Arrays adalah konsep utama bagaimana kita dalam menggunakan NumPy sepanjang pelajaran ini. Numpy Arrays biasanya digunakan untuk Vektor dan Matrix. Vector adalah 1D Arrays dan Matrix adalah 2D Arrays.

### Membuat NumPy Arrays

#### Dari List Python

In [1]:
#Membuat array dengan mengkonversi list
listku = [1,2,3,4,5]
listku

[1, 2, 3, 4, 5]

In [4]:
#Membuat array 1D dari list
np.array(listku)

array([1, 2, 3, 4, 5])

In [5]:
#Membuat array untuk matrix
matrixku = [[1,2,3],[4,5,6],[7,8,9]]
matrixku

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
#Mengkonversi array menjadi Matrix
np.array(matrixku)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **Beberapa Built-in Methods**

#### **arange**
Memanggil data berdasarkan jarak dan interval yang ditentukan

In [8]:
#Memanggil arange 0-10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#Memanggil arange 0-10 dengan interval setiap 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### **zeros dan ones**

Memanggil array angka zeros(0) dan ones(1)

In [10]:
#Memanggil array 1D berisi 0 dengan zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
#Memanggil matrix 5x5 berisi 0 dengan zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#Memanggil array 1D berisi 1 dengan ones
np.ones(3)

array([1., 1., 1.])

In [13]:
#Memanggil matrix 5x5 berisi 1 dengan ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### **linspace**

Memanggil dengan rentang angka berdasarkan jumlah angka yang ditentukan yang sesuai dengan interval angka tersebut

In [19]:
#Memanggil rentang angka 0-10 dengan jumlah 3 angka yang dimunculkan
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
#Memanggil rentang angka 0-10 dengan jumlah 50 angka yang dimunculkan
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### **eye**

Membuat matrix identitas

In [21]:
#Membuat matrix identitas dengan 5x5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **Random**

Numpy Juga memiliki fitur untuk membuat array dengan angka random

#### **rand**
Membuat array berdasarkan bentuk dan distribusinya rentang nilai 0 hingga 1

In [22]:
#Membuat array dengan 2 angka random dengan rand
np.random.rand(2)

array([0.49427024, 0.81496312])

In [23]:
#Membuat matrix 5x5 secara acak dengan distribusi nilai 0 hingga 1
np.random.rand(5,5)

array([[0.49556865, 0.31944213, 0.00768838, 0.43993451, 0.81285057],
       [0.33376486, 0.76833277, 0.03630232, 0.68631066, 0.8219982 ],
       [0.16456378, 0.38758148, 0.93869904, 0.61429517, 0.19206112],
       [0.39948491, 0.34613899, 0.33221809, 0.59642139, 0.11563127],
       [0.42413844, 0.93337339, 0.14634029, 0.74322911, 0.92596156]])

#### **rand**

Memanggil contoh dari "Standar Normal Distribution". Nilai randn lebih beragam

In [24]:
#Membuat array secara acak dengan randn
np.random.randn(2)

array([-0.13298733, -1.20721743])

In [25]:
#Membuat matrix 5x5 secara acak dengan randn dengan distribusi nilai untuk SND
np.random.randn(5,5)

array([[ 0.31107955, -1.2169571 ,  0.19552733,  1.58297946, -1.29136361],
       [-2.4541797 , -0.02505166, -1.23773247, -0.5777712 ,  0.23039136],
       [ 0.01717894, -0.54370267, -0.64839478,  4.06690988, -0.12371656],
       [ 0.10184651,  0.63020805, -1.14124238,  1.93243586, -0.47322362],
       [ 1.77701506, -0.86474092,  0.0726037 ,  0.07218932,  0.3577527 ]])

#### **randint**

Memanggil integers secara random dari nilai terendah hingga nilai tertinggi dengan interval yang di tentukan

In [26]:
#Memanggil angka secara acak dari 1-100
np.random.randint(1,100)

82

In [27]:
#Memanggil angka secara acak dari 1-100 dengan interval 10
np.random.randint(1,100,10)

array([51, 22, 81, 16, 81, 20, 40, 22, 47, 26])

### **Atribut Array dan Metode**

Perbedaan antara arange dengan randint

In [48]:
#Memanggil 10 integers dengan arange 
arr = np.arange(0,25,1)

In [51]:
#Memanggil 10 integers dengan randint
randarr = np.random.randint(0,25,25)

In [49]:
#Jika memanggil dengan arange maka hasil angkanya akan berurutan
#dan angka terakhir dalam fungsi digunakan sebagai interval
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
#Jika memanggil dengan randint maka hasil angkanya akan acak
#dan angka terakhir dalam fungsi digunakan sebagai jumlah angka yang muncul
randarr

array([22,  3, 23, 16, 18, 10,  2, 24, 19, 15, 13, 24, 19, 15, 23,  7, 16,
       11, 10,  4, 19,  5,  8,  8, 10])

#### **Reshape**

Memanggil array dengan data yang ada dengan bentuk baru

In [55]:
#Membuat bentuk baru matrix 5x5 dari list yang ada
arr = np.arange(0,25,1)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### **max,min,argmax,argmin**

Metode ini berguna untuk menemukan nilai maximum atau minimum, atau menemukan index posisi nilai max dan min

In [56]:
randarr

array([22,  3, 23, 16, 18, 10,  2, 24, 19, 15, 13, 24, 19, 15, 23,  7, 16,
       11, 10,  4, 19,  5,  8,  8, 10])

In [57]:
#Menentukan nilai maximum dari randarr
randarr.max()

24

In [58]:
#Menentukan nilai minimum dari randarr
randarr.min()

2

In [59]:
#Menentukan posisi dari nilai maximum dari randarr
randarr.argmax()

7

In [60]:
#Menentukan posisi dari nilai minimum dari randarr
randarr.argmin()

6

### **Shape**

Shape adalah attribute yang dimiliki oleh array

In [62]:
#Menentukan vector yang dimiliki oleh arr
arr.shape

(25,)

In [65]:
#Membuat matrix 1x25 dari nilai array
#Perhatikan bahwa ada 2 set brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
#Untuk mengetahui bentuk matrix diketahui matrix 1x25
arr.reshape(1,25).shape

(1, 25)

In [68]:
#Membuat matrix 25x1
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [69]:
#Untuk mengetahui bentuk matrix diketahui matrix 25x1
arr.reshape(25,1).shape

(25, 1)

#### **dtype**

Mengetaui type data dari objek array

In [70]:
#Mengetahui data arr
arr.dtype

dtype('int32')

## Selamat anda menyelesaikan bagian Numpy Array!!