## NumPy Indexing dan Selection

**Creator : Gian Antariksa**

Source  : 

Jose Portilla [Python for Data Science and Machinee Learning Bootcamp](https://www.udemy.com/python-for-data-science-and-machine-learning-bootcamp/)

Dalam kuliah kali ini kita akan membahas tentang bagaimana mengubah elemen atau grup elemen menjadi sebau array

In [1]:
#Memanggil library numpy
import numpy as np

In [4]:
#Membuat contoh array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing dan Selection

Cara termudah dalam memilih satu elemen atau beberapa elemen dari dalam array, dimana hampir mirip dengan memanggil lists dalam python

In [11]:
#Memanggil nilai dalam sebuah index
arr[9]

9

In [9]:
#Memanggil nilai dalam jangka jarak
arr[1:5]

array([1, 2, 3, 4])

In [12]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

### Broadcasting

Numpy Arrays berbeda dengan python pada umumnya karena memiliki kemampuan untuk melakukan broadcast

In [14]:
#Mengganti nilai dengan index dalam jarak 0-5 (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
#Melakukan definisi array ulang
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Mengambil bagian dalam array
potongan_array = arr[0:6]
potongan_array

array([0, 1, 2, 3, 4, 5])

In [18]:
#Mengganti semua nilai array
potongan_array[:]=99
potongan_array

array([99, 99, 99, 99, 99, 99])

Dalam mengganti array fitur ini mengganti array originalnya

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
#Melakukan copyin array
arr_tiruan = arr.copy()
arr_tiruan

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing Array 2D (Matrix)

Format dasar dari sebuah array 2D adalah [row,col] atau [row][col]. Direkomendasikan menggunakan Comma

In [22]:
#Membuat array 2D
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
#Mengambil baris ke 1 (Indexing)
arr_2d[1]

array([20, 25, 30])

In [25]:
#Mengambil satu data dari matrix
arr_2d[1][0]

20

In [26]:
#Mengambil data 2x2 dari matrix bagian atas kanan
#Direkomendasikan menggunakan comma
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
#Mengambil bagian baris bawah
arr_2d[2]

array([35, 40, 45])

In [28]:
#Mengambil bagian baris bawah dengan cara lain
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing
Fancy Indexing memungkinkan untuk memilih seluruh baris atau kolom 

In [45]:
#Membuat matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
#Panjang dari array
panjang_array = arr2d.shape[1]
panjang_array

10

In [47]:
#Membuat matrix 

for i in range(panjang_array):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [48]:
#Membuat index sesuai dengan yang diinginkan
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [49]:
arr2d[[1,3,6,8,9]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

### Selection

Menggunakan brackets untuk memilih berdasarkan komparasi operator (Comparison Operators)

In [53]:
#Membuat distribusi array dari 1-10
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#Menentukan booleans dari index berdasarkan Comparison
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
#Mendefine boolean dari array
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
#Mengambil nilai index yang memenuhi syarat 
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
#Memanggil nilai index dengan mentukan syarat yang diinginkan
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Selamat kamu telah menyelesaikan Numpy Indexing and Selection!!