## Numpy Operations

**Creator : Gian Antariksa**

Source  : 

Jose Portilla [Python for Data Science and Machinee Learning Bootcamp](https://www.udemy.com/python-for-data-science-and-machine-learning-bootcamp/)

### **Aritmatika**

Kamu dengan mudah bisa memanggil array dengan array aritmatik, atau skalar dengan array aritmatik

In [1]:
#Memanggil Library Numpy
import numpy as np
#Membuat array 0-9
arr = np.arange(0,10)

In [2]:
#Melakukan penjumlahan array
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
#Melakukan perkalian array
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
#melakukan pengurangan array
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
#Melakukan pembagian array
#Pembagian dengan angka 0 bukanlah sebuah error
#Hanya di gantikan dengan nan
arr/arr

D:\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
#Dan ketika melakukan pembagian dimana nilai 0 sebagai penyebut 
#Bukanlah sebuah error tetapi infinity
1/arr

D:\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### **Universal Array Functions**

Numpy dapat digunakan untuk berbagai [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), dimana fungsi utamanya adalah untuk melakukan operasi matematika yang digunakan untuk melakukan operasi dalam array

In [8]:
#Melakukan akar
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
#Melakukan exponensial
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
#Mengetahui nilai terbesar dalam array
#Sama seperti arr.max()
np.max(arr)

9

In [31]:
#Melakukan perhitungan Sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [30]:
#Melakukan perhitungan logaritmik
np.log(arr)

D:\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Selamat anda telah menyelesaikan NumPy Operations!!